# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  security.unprivilegedUsernsClone = true;
  boot = {
    kernelPackages = pkgs.linuxKernel.packages.linux_hardened;
    loader.systemd-boot.enable = true;
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "sr_mod"
        "zfs"
      ];
      kernelModules = [ "zfs" ];

      # unlock
      luks.forceLuksSupportInInitrd = true;
      systemd = {
        storePaths = [
          "${pkgs.clevis}"
          "${pkgs.curl}"
          "${pkgs.cryptsetup}"
          "${pkgs.luksmeta}"
          "${pkgs.gnused}"
          "${pkgs.tpm2-tools}"
          "${pkgs.jose}"
          "${pkgs.libpwquality}"
          "${pkgs.coreutils}"
          "${pkgs.gnugrep}"
          "${pkgs.bash}"
        ];
      };
    };

    kernel.sysctl = {
      "net.core.bpf_jit_harden" = 1;
    };

    supportedFilesystems = [ "zfs" ];

    zfs = {
      forceImportRoot = false;
      extraPools = [ "zroot" ];
    };
  };

  services.zfs = {
    autoScrub.enable = true;
    trim.enable = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/db1fad7d-522f-4e56-9388-5f3fc8a30e89";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7C82-26D3";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/b0575db3-17d4-42a1-a383-d956840ecc44";
    }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
